---
deployment:
  tasks:
    - export DEPLOYPATH=/home/doopy/public_html/pruebabypass/
    - cd $DEPLOYPATH
    - rm -rf
    - cd /home/doopy/repositories/
    - /bin/rsync -a pruebabypass/* $DEPLOYPATH
    - /bin/rsync -a vendorbypass/* $DEPLOYPATH
