---
deployment:
  tasks:
    - export DEPLOYPATH=/home/doopy/public_html/pruebabypass/
    - cd $DEPLOYPATH
    - rm -rf
    - cd
    - /bin/rsync -a /home/doopy/repositories/pruebabypass/ $DEPLOYPATH
    - /bin/rsync -a /home/doopy/repositories/vendorbypass/ $DEPLOYPATH
